language: csharp
solution: ./ManagedHook.sln
node_js:
  - "7"
mono: latest
dotnet: 2.1.301
install:
  - nuget restore -source "https://www.nuget.org/api/v2" ./ManagedHook.sln
script:
  - msbuild /p:Configuration=Release ./ManagedHook.sln
